namespace Prism.Framework;

/// <summary>
/// Anything generated by Prism will be marked with this attribute.
/// </summary>
[AttributeUsage(AttributeTargets.All)]
public class PrismGenerationAttribute : Attribute
{}